version: '3.8'

services:

  postgres:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped

  crawler:
    image: registry.github.com/papetier/crawler:v0.1.0
    environment:
      - LOG_LEVEL=debug
      - POSTGRES_DATABASE=postgres
      - POSTGRES_HOST=timescale
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
    restart: unless-stopped
